CREATE TABLE καταχώρηση_Πτήσεων (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DATE DATE NOT NULL,
    OPERATOR VARCHAR(255) NOT NULL,
    OPERATOR_ROLE VARCHAR(255) NOT NULL,
    UAV_TYPE VARCHAR(255) NOT NULL,
    AIRCRAFT VARCHAR(255) NOT NULL,
    BEGIN_FLIGHT TIME NOT NULL,
    FLIGHT_TIME INT NOT NULL,
    ΓΕΝΙΚΗ_ΔΝΣΗ VARCHAR(255) NOT NULL,
    Δ_ΝΣΗ_ΑΣΤΥΝ VARCHAR(255) NOT NULL,
    LoS VARCHAR(255) NOT NULL,
    FLIGHT_TYPE VARCHAR(255) NOT NULL,
    FLIGHT_PURPOSE VARCHAR(255) NOT NULL,
    ΔΙΑΤΑΓΗ VARCHAR(255) NOT NULL,
    ΠΑΡΑΤΗΡΗΣΕΙΣ TEXT
);